.TH "add_request_queue.h" 3 "Mon Apr 20 2020" "Elevator simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
add_request_queue.h \- contains declarations for add_request_queue function\&. Used to add passenger to queue  

.SH SYNOPSIS
.br
.PP
\fC#include 'structures\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBpassenger\fP * \fBadd_request_queue\fP (struct \fBpassenger\fP *head, struct \fBpassenger\fP passenger_queue)"
.br
.in -1c
.SH "Detailed Description"
.PP 
contains declarations for add_request_queue function\&. Used to add passenger to queue 


.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator simulation from the source code\&.
