.TH "add_passenger_floor.h" 3 "Mon Apr 20 2020" "Elevator simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
add_passenger_floor.h \- add passengers to the floor array  

.SH SYNOPSIS
.br
.PP
\fC#include 'structures\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBadd_passenger_floor\fP (struct \fBpassenger\fP *floor[], int index, struct \fBpassenger\fP passenger_info)"
.br
.in -1c
.SH "Detailed Description"
.PP 
add passengers to the floor array 


.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator simulation from the source code\&.
