.TH "count_passenger.h" 3 "Mon Apr 20 2020" "Elevator simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
count_passenger.h \- Counts the number of passengers from the input file\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "<<<<<<< HEAD=======>>>>>> int \fBcount_passenger\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Counts the number of passengers from the input file\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator simulation from the source code\&.
