.TH "create_floor_array.h" 3 "Mon Apr 20 2020" "Elevator simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
create_floor_array.h \- declaration for create_floor_array function -creates an array for floors with respective to input entered by user\&. Returns the array of floors\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBpassenger\fP * \fBcreate_floor_array\fP (int no_of_floors)"
.br
.in -1c
.SH "Detailed Description"
.PP 
declaration for create_floor_array function -creates an array for floors with respective to input entered by user\&. Returns the array of floors\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator simulation from the source code\&.
