.TH "C:/Users/Work/git_repo/elevator_simulator/include/dynamic_functions.h" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/include/dynamic_functions.h \- Simply imports all the headers of the different of dynamic function\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'cli_update\&.h'\fP
.br
\fC#include 'input_after_stop\&.h'\fP
.br
\fC#include 'input_static_dynamic\&.h'\fP
.br
\fC#include 'emergency_stop_handling\&.h'\fP
.br
\fC#include 'read_user_input_validate\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Simply imports all the headers of the different of dynamic function\&. 


.br
 
.PP
Definition in file \fBdynamic_functions\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
