.TH "elevator" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elevator \- structure to store important information about an elevator\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <structures\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBmoving\fP"
.br
.RI "Is the elevator moving? True 1 or False(stationary) 0\&. "
.ti -1c
.RI "bool \fBbetween_floor\fP"
.br
.RI "Is elevator between floors\&. True 1 between floors\&. "
.ti -1c
.RI "bool \fBdirection_up\fP"
.br
.RI "Is the elevator going up? True 1 for going up\&. "
.ti -1c
.RI "bool \fBdirection_down\fP"
.br
.RI "Is the elevator going down? True 1 for going down\&. "
.ti -1c
.RI "bool * \fBstop_at_floor\fP"
.br
.RI "points to boolean array of floors and shows if the elevator will stop at a certain floor or not\&. "
.ti -1c
.RI "unsigned int \fBpassenger_count\fP"
.br
.RI "count of passenger occupying the elevator "
.ti -1c
.RI "unsigned int \fBmax_passenger\fP"
.br
.RI "Maximum number of passengers the lift can accomodate\&. "
.ti -1c
.RI "unsigned int \fBcur_floor\fP"
.br
.RI "The current floor of the elevator\&. Floors start at 1\&. "
.ti -1c
.RI "unsigned int \fBtimer\fP"
.br
.RI "Time clock untill the next floor\&. "
.ti -1c
.RI "struct \fBpassenger\fP * \fBpassenger_arr\fP"
.br
.RI "points to a array of struct pasenger of size max_passenger\&. "
.in -1c
.SH "Detailed Description"
.PP 
structure to store important information about an elevator\&. 

Stores information about the elevator such as direction of travel, the floors to stop at\&. The maximum number of passengers the lift can accomodate and the current passengers in the lift and their information\&. and time it takes to go to the reach next floor\&. 
.PP
Definition at line 35 of file structures\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
