.TH "C:/Users/Work/git_repo/elevator_simulator/include/emergency_stop_handling.h" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/include/emergency_stop_handling.h \- contains declaration for the emergency_stop_handling() function\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'structures\&.h'\fP
.br
\fC#include 'globals\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBemergency_stop_handling\fP (struct \fBelevator\fP ele[], unsigned int *timer)"
.br
.in -1c
.SH "Detailed Description"
.PP 
contains declaration for the emergency_stop_handling() function\&. 


.PP
\fBAuthor\fP
.RS 4
Divyalakshmi Padmanaban 
.RE
.PP

.PP
Definition in file \fBemergency_stop_handling\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
