.TH "C:/Users/Work/git_repo/elevator_simulator/include/functions.h" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/include/functions.h \- Simply contains all the headers of the different function\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'structures\&.h'\fP
.br
\fC#include 'globals\&.h'\fP
.br
\fC#include 'add_passenger_floor\&.h'\fP
.br
\fC#include 'add_request_queue\&.h'\fP
.br
\fC#include 'count_passenger\&.h'\fP
.br
\fC#include 'create_elevator_array\&.h'\fP
.br
\fC#include 'create_floor_array\&.h'\fP
.br
\fC#include 'input_floors\&.h'\fP
.br
\fC#include 'input_lifts\&.h'\fP
.br
\fC#include 'is_lift_on_floor\&.h'\fP
.br
\fC#include 'moving_lift_down\&.h'\fP
.br
\fC#include 'moving_lift_up\&.h'\fP
.br
\fC#include 'passengers_drop\&.h'\fP
.br
\fC#include 'passengers_take_in\&.h'\fP
.br
\fC#include 'read_passenger\&.h'\fP
.br
\fC#include 'remove_passenger_floor\&.h'\fP
.br
\fC#include 'remove_passenger_queue\&.h'\fP
.br
\fC#include 'travel_log_file\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Simply contains all the headers of the different function\&. 


.br
 
.PP
Definition in file \fBfunctions\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
