.TH "functions.h" 3 "Mon Apr 20 2020" "Elevator simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
functions.h \- Simply contains all the headers of the different function\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'structures\&.h'\fP
.br
\fC#include 'globals\&.h'\fP
.br
\fC#include 'moving_lift_down\&.h'\fP
.br
\fC#include 'input_lifts\&.h'\fP
.br
\fC#include 'add_request_queue\&.h'\fP
.br
\fC#include 'remove_passenger_queue\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Simply contains all the headers of the different function\&. 


.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator simulation from the source code\&.
