.TH "C:/Users/Work/git_repo/elevator_simulator/src/globals.c" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/src/globals.c \- Contains the global variables used in the program\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'globals\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "unsigned int \fBelevator_count\fP"
.br
.ti -1c
.RI "unsigned int \fBpassenger_count\fP"
.br
.ti -1c
.RI "unsigned int \fBfloor_count\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the global variables used in the program\&. 


.PP
Definition in file \fBglobals\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "unsigned int elevator_count"
Total number of elevators in the bulding 
.PP
Definition at line 10 of file globals\&.c\&.
.SS "unsigned int floor_count"
The floor count of the building 
.PP
Definition at line 16 of file globals\&.c\&.
.SS "unsigned int passenger_count"
Total number of passengers checked from the passengers file text 
.PP
Definition at line 13 of file globals\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
