.TH "C:/Users/Work/git_repo/elevator_simulator/src/input_static_dynamic.c" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/src/input_static_dynamic.c \- Prompts user for type of simulation they want to run\&.  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/input_static_dynamic\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBinput_static_dynamic\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Prompts user for type of simulation they want to run\&. 

@Author Ritika Arora
.PP
@detail Asks user the type of simulation he wants to run\&. For, static, he has to press 1 and for dynamic, he has to press 2\&. If 1 is entered by the user, then it will assign 0 to the local variable simulation_type\&. If 2 is entered, then it assigns 1 to the variable\&.
.PP
\fBParameters\fP
.RS 4
\fIvoid\fP The function takes no inputs
.br
\fIsimulation_type\fP contains the value to be returned to decide which type of simulation runs\&.
.RE
.PP
\fBReturns\fP
.RS 4
int Returns 0 for static simulation, 1 for dynamic simulation and -1 for invalid input\&. 
.RE
.PP

.PP
Definition in file \fBinput_static_dynamic\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
