.TH "input_lifts.h" 3 "Mon Apr 20 2020" "Elevator simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
input_lifts.h \- Inputs the number of lifts from user\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBinput_lifts\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Inputs the number of lifts from user\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator simulation from the source code\&.
