.TH "C:/Users/Work/git_repo/elevator_simulator/include/input_after_stop.h" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/include/input_after_stop.h \- Gets the user input to determine status of simulation after encountering emergency stop\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBinput_after_stop\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Gets the user input to determine status of simulation after encountering emergency stop\&. 


.PP
\fBAuthor\fP
.RS 4
Hariprasad Munusamy - HariprasadMunusamy@cmail.carleton.ca 
.RE
.PP

.PP
Definition in file \fBinput_after_stop\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
