.TH "input_floors.h" 3 "Mon Apr 20 2020" "Elevator simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
input_floors.h \- Obtains the floor count-Total number of floors in the building\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBinput_floors\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Obtains the floor count-Total number of floors in the building\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator simulation from the source code\&.
