.TH "C:/Users/Work/git_repo/elevator_simulator/include/input_static_dynamic.h" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/include/input_static_dynamic.h \- Has the declaration for input_static_dynamic function\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBinput_static_dynamic\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Has the declaration for input_static_dynamic function\&. 


.PP
\fBAuthor\fP
.RS 4
Ritika Arora
.RE
.PP
@detail The function to decide which type of simulation user wants to run\&.
.PP
\fBParameters\fP
.RS 4
\fIvoid\fP The function takes no inputs
.RE
.PP
\fBReturns\fP
.RS 4
int returns an integer value 
.RE
.PP

.PP
Definition in file \fBinput_static_dynamic\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
