.TH "is_lift_on_floor.h" 3 "Mon Apr 20 2020" "Elevator simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
is_lift_on_floor.h \- Contains declaration for is_lift_on_floor function -Reads the elevator structure's attribute moving_floor\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBis_lift_on_floor\fP (struct \fBelevator\fP elev[], int index)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains declaration for is_lift_on_floor function -Reads the elevator structure's attribute moving_floor\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator simulation from the source code\&.
