.TH "C:/Users/Work/git_repo/elevator_simulator/include/is_lift_empty.h" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/include/is_lift_empty.h \- Has the declaration for the is_lift_empty function @detail The function has two input parameters: one is an array of elevators of elevator type @detail and the other is the index of the array which can be used as the number of the elevator\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'structures\&.h'\fP
.br
\fC#include 'globals\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBis_lift_empty\fP (struct \fBelevator\fP elevator_arr[], unsigned int index)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Has the declaration for the is_lift_empty function @detail The function has two input parameters: one is an array of elevators of elevator type @detail and the other is the index of the array which can be used as the number of the elevator\&. 


.PP
Definition in file \fBis_lift_empty\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
