.TH "C:/Users/Work/git_repo/elevator_simulator/include/max_waiting_time.h" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/include/max_waiting_time.h \- Has the declaration for the max_waiting_time function @detail The function has one input parameter: time_difference which is the difference between the time passenger arrived and the time he got into the elevator\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'structures\&.h'\fP
.br
\fC#include 'globals\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBmax_waiting_time\fP (float time_difference)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Has the declaration for the max_waiting_time function @detail The function has one input parameter: time_difference which is the difference between the time passenger arrived and the time he got into the elevator\&. 


.PP
\fBReturns\fP
.RS 4
float returns the maximum time taken by a passenger 
.RE
.PP

.PP
Definition in file \fBmax_waiting_time\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
