.TH "moving_lift_down.h" 3 "Mon Apr 20 2020" "Elevator simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moving_lift_down.h \- contains declaration for structure moving_lift_down function that changes the direction of lift\&. the function is defination found in moving_lift_down\&.c  

.SH SYNOPSIS
.br
.PP
\fC#include 'structures\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmoving_lift_down\fP (struct \fBelevator\fP elevator_arr[], unsigned int index)"
.br
.in -1c
.SH "Detailed Description"
.PP 
contains declaration for structure moving_lift_down function that changes the direction of lift\&. the function is defination found in moving_lift_down\&.c 


.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator simulation from the source code\&.
