.TH "passenger" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
passenger \- structure to store important information about a passenger\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <structures\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBin_elevator\fP"
.br
.RI "Stores whether passegner is in elevator\&. "
.ti -1c
.RI "unsigned int \fBarrival_time\fP"
.br
.RI "stores arrival time of the passenger "
.ti -1c
.RI "unsigned int \fBarrival_floor\fP"
.br
.RI "stores the arrival_floor of the passenger "
.ti -1c
.RI "unsigned int \fBdest_floor\fP"
.br
.RI "stores the destination floor of the passenger "
.ti -1c
.RI "unsigned int \fBid\fP"
.br
.RI "stores the passenger_id of the passenger "
.ti -1c
.RI "struct \fBpassenger\fP * \fBnext\fP"
.br
.RI "stores address of the next node in case of creation of queues "
.in -1c
.SH "Detailed Description"
.PP 
structure to store important information about a passenger\&. 

Stores the arrival time and floor and destination floor of the passenger\&. as well as the passenger id\&. There is a next passenger pointer to create queues 
.PP
Definition at line 16 of file structures\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
