.TH "passengers_drop.c" 3 "Wed Apr 22 2020" "Elevator_simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
passengers_drop.c \- The function takes in the elevator_array\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'passengers_drop\&.h'\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include 'globals\&.h'\fP
.br
\fC#include 'structures\&.h'\fP
.br
\fC#include 'travel_log_file\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpassengers_drop\fP (struct elevator elevator_arr[], int index, struct passenger *floor_arr[], int cur_floor, unsigned int event_time)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The function takes in the elevator_array\&. 


.PP
\fBAuthor\fP
.RS 4
Hariprasad Munusamy - HariprasadMunusamy@cmail.carleton.ca 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int passengers_drop (struct elevator elevator_arr[], int index, struct passenger * floor_arr[], int cur_floor, unsigned int event_time)"
Removes the passenger from the floor and the elevator array\&.
.PP
\fBParameters\fP
.RS 4
\fIThe\fP function takes in elevator structure,index,passenger floor array,current floor and time
.RE
.PP
\fBReturns\fP
.RS 4
The function return elevator array 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator_simulation from the source code\&.
