.TH "passengers_take_in.h" 3 "Mon Apr 20 2020" "Elevator simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
passengers_take_in.h \- contains declarations for passenger_take_in function\&. Used to add passenger to the provided elevator array entry  

.SH SYNOPSIS
.br
.PP
\fC#include 'structures\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpassengers_take_in\fP (struct \fBelevator\fP elevator_arr[], int index, struct \fBpassenger\fP floor_arr[], int cur_floor)"
.br
.in -1c
.SH "Detailed Description"
.PP 
contains declarations for passenger_take_in function\&. Used to add passenger to the provided elevator array entry 


.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator simulation from the source code\&.
