.TH "passengers_drop.h" 3 "Mon Apr 20 2020" "Elevator simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
passengers_drop.h \- drops the passeger in corresponding floor  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpassengers_drop\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
drops the passeger in corresponding floor 


.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator simulation from the source code\&.
