.TH "C:/Users/Work/git_repo/elevator_simulator/include/read_user_input_validate.h" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/include/read_user_input_validate.h \- contains declarations for read_user_input_validate function\&. Reads the passenger information from the user console and adds it to the passenger structure after validating  

.SH SYNOPSIS
.br
.PP
\fC#include 'structures\&.h'\fP
.br
\fC#include 'globals\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBread_user_input_validate\fP (struct \fBpassenger\fP *passenger_info, unsigned int timer)"
.br
.in -1c
.SH "Detailed Description"
.PP 
contains declarations for read_user_input_validate function\&. Reads the passenger information from the user console and adds it to the passenger structure after validating 


.PP
\fBAuthor\fP
.RS 4
Ritika Arora
.RE
.PP
\fBParameters\fP
.RS 4
\fIpassenger_info\fP pointer to the passenger structure containing data of the passenger\&. 
.br
\fItimer\fP to get the time of simulation and store as time of arrival
.RE
.PP
\fBReturns\fP
.RS 4
void returns nothing 
.RE
.PP

.PP
Definition in file \fBread_user_input_validate\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
