.TH "C:/Users/Work/git_repo/elevator_simulator/src/read_user_input_validate.c" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/src/read_user_input_validate.c \- Reads the input from the console and adds to the passenger struct after validating\&.  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/read_user_input_validate\&.h'\fP
.br
\fC#include '\&.\&./include/globals\&.h'\fP
.br
\fC#include '\&.\&./include/structures\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBread_user_input_validate\fP (struct \fBpassenger\fP *passenger_info, unsigned int timer)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reads the input from the console and adds to the passenger struct after validating\&. 


.PP
\fBAuthor\fP
.RS 4
Ritika Arora
.RE
.PP
Reads the passenger details from the user console\&. Validates the inputs given\&. Then, adds the inputs taken to the passenger structure
.PP
\fBParameters\fP
.RS 4
\fIpassenger_info\fP pointer to the passenger structure containing data of the passenger\&. 
.br
\fItimer\fP to get the time of simulation and store as time of arrival
.RE
.PP
\fBReturns\fP
.RS 4
void returns nothing 
.RE
.PP

.PP
Definition in file \fBread_user_input_validate\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
