.TH "C:/Users/Work/git_repo/elevator_simulator/include/read_passenger.h" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/include/read_passenger.h \- Reads the input file for passenger id,arrival time,starting floor and destination floor\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'structures\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBread_passenger\fP (struct \fBpassenger\fP *p)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reads the input file for passenger id,arrival time,starting floor and destination floor\&. 


.PP
Definition in file \fBread_passenger\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
