.TH "remove_passenger_queue.h" 3 "Mon Apr 20 2020" "Elevator simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
remove_passenger_queue.h \- contains the declaration for remove_passenger_queue function that remoove passenger from a queue  

.SH SYNOPSIS
.br
.PP
\fC#include 'structures\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBpassenger\fP * \fBremove_passenger_queue\fP (int index, struct \fBpassenger\fP *head)"
.br
.in -1c
.SH "Detailed Description"
.PP 
contains the declaration for remove_passenger_queue function that remoove passenger from a queue 


.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator simulation from the source code\&.
