.TH "remove_passenger_floor.h" 3 "Mon Apr 20 2020" "Elevator simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
remove_passenger_floor.h \- Removes the passenger details from floor specified\&.Returns 1 on successful deletion of passenger details from specified floor\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'structures\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBremove_passenger_floor\fP (struct \fBpassenger\fP *floor[], int cur_floor)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Removes the passenger details from floor specified\&.Returns 1 on successful deletion of passenger details from specified floor\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator simulation from the source code\&.
