.TH "C:/Users/Work/git_repo/elevator_simulator/include/simulations.h" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/include/simulations.h \- this file simply includes the header files of the two simulations\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'static_simulation\&.h'\fP
.br
\fC#include 'dynamic_simulation\&.h'\fP
.br

.SH "Detailed Description"
.PP 
this file simply includes the header files of the two simulations\&. 


.PP
\fBAuthor\fP
.RS 4
Maaz Jamal 
.RE
.PP

.PP
Definition in file \fBsimulations\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
