.TH "C:/Users/Work/git_repo/elevator_simulator/include/structures.h" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/include/structures.h \- contains declarations for structure passenger, elevator to be used in the program\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBpassenger\fP"
.br
.RI "structure to store important information about a passenger\&. "
.ti -1c
.RI "struct \fBelevator\fP"
.br
.RI "structure to store important information about an elevator\&. "
.in -1c
.SH "Detailed Description"
.PP 
contains declarations for structure passenger, elevator to be used in the program\&. 


.PP
Definition in file \fBstructures\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
