.TH "structures.h" 3 "Mon Apr 20 2020" "Elevator simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
structures.h \- contains declarations for structure passenger, elevator to be used in the program\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBpassenger\fP"
.br
.RI "structure for to store important information about a passenger\&. "
.ti -1c
.RI "struct \fBelevator\fP"
.br
.RI "structure for to store important information about a elevator\&. "
.in -1c
.SH "Detailed Description"
.PP 
contains declarations for structure passenger, elevator to be used in the program\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator simulation from the source code\&.
