.TH "C:/Users/Work/git_repo/elevator_simulator/test/test_input_lifts.c" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/test/test_input_lifts.c \- This file contains function test_input_lifts() that provides unit testing for function \fBinput_lifts()\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'input_lifts\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest_input_lifts\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains function test_input_lifts() that provides unit testing for function \fBinput_lifts()\fP\&. 


.PP
\fBAuthor\fP
.RS 4
Maaz Jamal 
.RE
.PP

.PP
Definition in file \fBtest_input_lifts\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
