.TH "C:/Users/Work/git_repo/elevator_simulator/test/test_average_waiting_time.c" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/test/test_average_waiting_time.c \- tests the average_waiting_time function if working fine or not  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include '\&.\&./include/globals\&.h'\fP
.br
\fC#include '\&.\&./include/average_waiting_time\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest_average_waiting_time\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
tests the average_waiting_time function if working fine or not 


.PP
\fBAuthor\fP
.RS 4
Ritika Arora
.RE
.PP
@detail The function is to test average_waiting_time function for given inputs, the function returns right values or not\&. The average_waiting_time function is called with different inputs and its output is stored in one local variable\&. The max_time local variable should give the maximum of all the inputs given\&. The function checks if the max_time stores maximum of the inputs given to the max_waiting_time function , then the test passes and prints the result on console as well as writes on a file\&.
.PP
\fBParameters\fP
.RS 4
\fINo\fP input is given to the function
.RE
.PP
\fBReturns\fP
.RS 4
void The function returns nothing\&. 
.RE
.PP

.PP
Definition in file \fBtest_average_waiting_time\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
