.TH "C:/Users/Work/git_repo/elevator_simulator/test/test_cli_update.c" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/test/test_cli_update.c \- contains test case for \fBcli_update()\fP function  

.SH SYNOPSIS
.br
.PP
\fC#include 'cli_update\&.h'\fP
.br
\fC#include 'structures\&.h'\fP
.br
\fC#include 'globals\&.h'\fP
.br
\fC#include 'stdio\&.h'\fP
.br
\fC#include 'stdlib\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest_cli_update\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBelevator\fP \fBdummy1\fP = {1,0,0,1,0,3,10,30,15,0}"
.br
.ti -1c
.RI "struct \fBelevator\fP \fBdummy2\fP = {0,0,0,1,0,6,10,2,3,0}"
.br
.ti -1c
.RI "struct \fBelevator\fP \fBdummy3\fP = {1,0,0,0,0,0,10,5,0,0}"
.br
.in -1c
.SH "Detailed Description"
.PP 
contains test case for \fBcli_update()\fP function 

Tests the \fBcli_update()\fP function for basic screen clear test, display test and repeated function calls test\&.
.PP
\fBAuthor\fP
.RS 4
Maaz Jamal 
.RE
.PP

.PP
Definition in file \fBtest_cli_update\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
