.TH "C:/Users/Work/git_repo/elevator_simulator/test/test_read_passenger.c" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/test/test_read_passenger.c \- contains tests for \fBread_passenger()\fP function\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'structures\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest_read_passenger\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
contains tests for \fBread_passenger()\fP function\&. 


.PP
Definition in file \fBtest_read_passenger\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
