.TH "C:/Users/Work/git_repo/elevator_simulator/test/test_create_floor_array.c" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/test/test_create_floor_array.c \- To test create_floor_array function which creates array for every floor\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBpassenger\fP"
.br
.RI "structure to store important information about a passenger\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest_create_floor_array\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBpassenger\fP \fBdummy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
To test create_floor_array function which creates array for every floor\&. 


.PP
\fBAuthor\fP
.RS 4
Hariprasad Munusamy - HariprasadMunusamy@cmail.carleton.ca 
.RE
.PP
\fBReturns\fP
.RS 4
Writes the test case log in output file 
.RE
.PP

.PP
Definition in file \fBtest_create_floor_array\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
