.TH "C:/Users/Work/git_repo/elevator_simulator/test/test_passenger_take_in.c" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/test/test_passenger_take_in.c \- This file contains function test_passenger_take_in() that provides unit testing for function passenger_take_in()\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'passengers_take_in\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'globals\&.h'\fP
.br
\fC#include 'structures\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtest_passenger_take_in\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBelevator\fP \fBdummy\fP = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}"
.br
.ti -1c
.RI "struct \fBelevator\fP \fBdummy_2\fP = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}"
.br
.ti -1c
.RI "struct \fBpassenger\fP \fBdummy_pass\fP = {1, 0, 0, 4, 0, 0}"
.br
.ti -1c
.RI "FILE * \fBf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains function test_passenger_take_in() that provides unit testing for function passenger_take_in()\&. 


.PP
\fBAuthor\fP
.RS 4
Maaz Jamal 
.RE
.PP

.PP
Definition in file \fBtest_passenger_take_in\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
