.TH "C:/Users/Work/git_repo/elevator_simulator/test/test_cases.c" 3 "Fri Apr 24 2020" "Version 2.0" "Elevator Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Work/git_repo/elevator_simulator/test/test_cases.c \- Contains all the tests and menue logic to choose each test\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'functions\&.h'\fP
.br
\fC#include 'test_functions\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest_cases\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains all the tests and menue logic to choose each test\&. 


.PP
Definition in file \fBtest_cases\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elevator Simulator from the source code\&.
